### ISSUE TITLE
url parser error involving ")"

### ISSUE THREAD

**Issue by pokeball99** [slatinsky/DiscordChatExporter-frontend#1] opened 2022-10-24 21:37 UTC
![image](https://user-images.githubusercontent.com/9436061/197634400-f493e8ad-684d-49bc-8961-b69a073bcd47.png)

**Comment by slatinsky** [comment] 2022-10-24 21:48
Hello,

the project now uses [brussell98/discord-markdown](https://github.com/brussell98/discord-markdown) dependency to parse markdown in messages. That includes links too.

This issue will be fixed after custom message parser will be made or after it will be fixed in [brussell98/discord-markdown](https://github.com/brussell98/discord-markdown).

**Comment by slatinsky** [comment] 2023-02-11 15:18
The issue it too rare to be worth the time to fix it. Also the issue is in the dependency discord-markdown.
This doesn't mean that I won't fix/workaround less rare issues with message rendering. 
Closing as wontfix.

**Closed by slatinsky** 2023-02-11 15:18 UTC
Labels: wontfix
